# Generated by Django 5.2.1 on 2025-06-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method_type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Bank Transfer', 'Bank Transfer'), ('Online', 'Online Payment'), ('Mobile', 'Mobile Payment'), ('Voucher', 'Voucher/Coupon')], default='Cash', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('Full', 'Full Payment'), ('Partial', 'Partial Payment'), ('Refund', 'Refund')], default='Full', max_length=10),
        ),
    ]
